keycloak:
  auth-server-url: https://login.aws.innovation-hub.de/auth
  bearer-only: true
  cors: false
  principal-attribute: preferred_username
  realm: innovation-hub-bergisches-rheinland
  resource: prox-professor-profile-service
server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: professor-profile-service
  datasource:
    password: professor-profile-service
    url: jdbc:postgresql://professor-profile-db:5432/professor-profile-db
    username: professor-profile-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
springdoc:
  # By default Springdoc will remove schemas which do not have references.
  remove-broken-reference-definitions: false
prox:
  services:
    project-service:
      url: https://api.prox.aws.innovation-hub.de
